import streamlit as st
import pandas as pd
import numpy as np
import altair as alt

# The entire page is now wrapped in a condition to check for the 'patient' role.
if st.session_state.user_role == "patient":
    st.title("My Chronic Care Coach 📈")
    st.write("Track your health trends and get personalized insights.")

    st.markdown("### My Dashboard")
    st.markdown("#### BP and Glucose Trends")
    
    # Placeholder for a real chart
    data = pd.DataFrame({
        'date': pd.to_datetime(pd.date_range(start='2025-01-01', periods=90, freq='D')),
        'systolic': np.random.randint(110, 150, 90),
        'glucose': np.random.randint(80, 120, 90)
    })
    
    c = alt.Chart(data).mark_line().encode(
        x='date:T',
        y='systolic:Q',
        tooltip=['date', 'systolic']
    ).interactive()
    st.altair_chart(c, use_container_width=True)
    
    # The "Alerts & Nudges" section serves as the output display.
    # In a real app, this would be dynamically generated by the model.
    st.markdown("---")
    st.markdown("#### Alerts & Nudges from My Coach")
    st.warning("⚠️ **Alert:** Your systolic BP has been trending up. Try reducing salt intake.")
    st.info("💡 **Nudge:** Remember to log your BP reading tonight! You can do it!")

    col1, col2 = st.columns(2)
    with col1:
        st.button("Log New Reading", use_container_width=True)
    with col2:
        st.button("Download My Report", use_container_width=True)

# If the user is not a patient, this message is shown.
else:
    st.warning("This feature is available for patients only.")
    st.page_link("pages/1_🏠_Home.py", label="Return to Dashboard", icon="🏠")